version: "3.8"
services:
  my_rabbitmq:
    image: rabbitmq:3-management
    container_name: 'parking-rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    build: ../parking
    container_name: 'parking-backend'
    ports:
      - "5000:5000"
    depends_on:
      - "my_rabbitmq"
    command: sh -c "dockerize -wait tcp://my_rabbitmq:5672 -timeout 60s -wait-retry-interval 10s /opt/app/start-service.sh"